version: '2'
services:

  db:
    image: mysql:5.7
    container_name: rails-mysql
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d/
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    env_file: .env

  web:
    build: .
    command: ["/bin/sh", "-c", "yarn install && gem update && bundle update && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    volumes:
      - .:/product_name
    ports:
      - "3000:3000"
    depends_on:
      - db
