version: '2'
services:

  db:
    image: mysql:8.0
    container_name: rails-mysql
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d/
    command: mysqld --collation-server=utf8mb4_unicode_ci
    ports:
      - 3310:3310
    env_file: .env

  web:
    build: .
    command: ["/bin/sh", "-c", "yarn install && bundle exec rails s -p 3000"]
    volumes:
      - .:/product_name
    ports:
      - "3000:3000"
    depends_on:
      - db
