version: '2'
services:

  db:
    image: mysql:8.0
    container_name: rails-mysql
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d/
    command: mysqld --collation-server=utf8mb4_unicode_ci
    ports:
      - 3310:3310
    env_file: .env

  web:
    build: .
    command: ["/bin/sh", "-c", "yarn install && rails new product_name && chmod go-w /bundle/bin/ && chmod go-w /bundle/ && cd product_name && bundle exec rails s -p 3000"]
    volumes:
      - .:/product_name
      - .:Gemfile.lock
      - .:Gemfile
    ports:
      - "3000:3000"
    depends_on:
      - db
